upgrade shade to 1.31.0
Previous version 1.29.0 was incompatible with openstacksdk 0.28.0.
Caused the following error when running tests:
```
ImportError: cannot import name 'task_manager'
```